// ===== GymAmigo databases =====
// MET-waarden: gebruikt voor caloriebereking (kcal = MET × gewicht(kg) × uren)

const EXERCISES = [
  // Borst
  { id: "bench", name: "Bankdrukken (barbell)", muscle: "Borst", met: 6.0 },
  { id: "dbbench", name: "Bankdrukken (dumbbells)", muscle: "Borst", met: 6.0 },
  { id: "incbench", name: "Incline bankdrukken", muscle: "Borst", met: 6.0 },
  { id: "chestpress", name: "Chest press (machine)", muscle: "Borst", met: 4.5 },
  { id: "flyes", name: "Dumbbell flyes", muscle: "Borst", met: 3.8 },
  { id: "cableflyes", name: "Cable flyes / crossover", muscle: "Borst", met: 3.8 },
  { id: "pecdeck", name: "Pec deck (machine)", muscle: "Borst", met: 3.8 },
  { id: "pushup", name: "Push-ups", muscle: "Borst", met: 5.0, bodyweight: true },
  { id: "dips", name: "Dips", muscle: "Borst", met: 5.5, bodyweight: true },

  // Rug
  { id: "deadlift", name: "Deadlift", muscle: "Rug", met: 6.5 },
  { id: "pullup", name: "Pull-ups / optrekken", muscle: "Rug", met: 6.0, bodyweight: true },
  { id: "latpull", name: "Lat pulldown", muscle: "Rug", met: 4.5 },
  { id: "bbrow", name: "Barbell row", muscle: "Rug", met: 6.0 },
  { id: "dbrow", name: "Dumbbell row", muscle: "Rug", met: 5.0 },
  { id: "cablerow", name: "Seated cable row", muscle: "Rug", met: 4.5 },
  { id: "tbarrow", name: "T-bar row", muscle: "Rug", met: 5.5 },
  { id: "facepull", name: "Face pulls", muscle: "Rug", met: 3.8 },
  { id: "hyperext", name: "Back extension", muscle: "Rug", met: 4.0, bodyweight: true },

  // Benen
  { id: "squat", name: "Squat (barbell)", muscle: "Benen", met: 6.5 },
  { id: "frontsquat", name: "Front squat", muscle: "Benen", met: 6.5 },
  { id: "legpress", name: "Leg press", muscle: "Benen", met: 5.0 },
  { id: "lunge", name: "Lunges", muscle: "Benen", met: 5.5 },
  { id: "bulgsplit", name: "Bulgarian split squat", muscle: "Benen", met: 5.5 },
  { id: "rdl", name: "Romanian deadlift", muscle: "Benen", met: 6.0 },
  { id: "legext", name: "Leg extension", muscle: "Benen", met: 3.8 },
  { id: "legcurl", name: "Leg curl", muscle: "Benen", met: 3.8 },
  { id: "hipthrust", name: "Hip thrust", muscle: "Benen", met: 5.0 },
  { id: "calfraise", name: "Calf raises", muscle: "Benen", met: 3.5 },
  { id: "gobsquat", name: "Goblet squat", muscle: "Benen", met: 5.5 },

  // Schouders
  { id: "ohp", name: "Overhead press (barbell)", muscle: "Schouders", met: 5.5 },
  { id: "dbshpress", name: "Shoulder press (dumbbells)", muscle: "Schouders", met: 5.0 },
  { id: "latraise", name: "Lateral raises", muscle: "Schouders", met: 3.5 },
  { id: "frontraise", name: "Front raises", muscle: "Schouders", met: 3.5 },
  { id: "reardelt", name: "Reverse flyes (rear delt)", muscle: "Schouders", met: 3.5 },
  { id: "shrugs", name: "Shrugs", muscle: "Schouders", met: 3.5 },
  { id: "arnold", name: "Arnold press", muscle: "Schouders", met: 5.0 },

  // Biceps
  { id: "bbcurl", name: "Barbell curl", muscle: "Biceps", met: 3.8 },
  { id: "dbcurl", name: "Dumbbell curl", muscle: "Biceps", met: 3.8 },
  { id: "hammercurl", name: "Hammer curl", muscle: "Biceps", met: 3.8 },
  { id: "preachcurl", name: "Preacher curl", muscle: "Biceps", met: 3.5 },
  { id: "cablecurl", name: "Cable curl", muscle: "Biceps", met: 3.5 },

  // Triceps
  { id: "tripush", name: "Triceps pushdown (cable)", muscle: "Triceps", met: 3.5 },
  { id: "skull", name: "Skull crushers", muscle: "Triceps", met: 3.8 },
  { id: "ohtri", name: "Overhead triceps extension", muscle: "Triceps", met: 3.5 },
  { id: "closebench", name: "Close-grip bankdrukken", muscle: "Triceps", met: 5.5 },
  { id: "kickback", name: "Triceps kickback", muscle: "Triceps", met: 3.2 },

  // Core
  { id: "plank", name: "Plank (per 30 sec = 1 hh.)", muscle: "Core", met: 3.5, bodyweight: true },
  { id: "crunch", name: "Crunches", muscle: "Core", met: 3.8, bodyweight: true },
  { id: "legraise", name: "Leg raises", muscle: "Core", met: 4.0, bodyweight: true },
  { id: "russian", name: "Russian twists", muscle: "Core", met: 4.0, bodyweight: true },
  { id: "cablecrunch", name: "Cable crunch", muscle: "Core", met: 3.8 },
  { id: "hangknee", name: "Hanging knee raises", muscle: "Core", met: 4.5, bodyweight: true },
  { id: "abwheel", name: "Ab wheel rollout", muscle: "Core", met: 4.5, bodyweight: true },

  // Cardio (invoer in minuten)
  { id: "run", name: "Hardlopen (loopband)", muscle: "Cardio", met: 9.8, cardio: true },
  { id: "jog", name: "Joggen (rustig)", muscle: "Cardio", met: 7.0, cardio: true },
  { id: "walk", name: "Wandelen (stevig)", muscle: "Cardio", met: 4.3, cardio: true },
  { id: "bike", name: "Fietsen (hometrainer)", muscle: "Cardio", met: 6.8, cardio: true },
  { id: "row", name: "Roeien (machine)", muscle: "Cardio", met: 7.0, cardio: true },
  { id: "elliptical", name: "Crosstrainer", muscle: "Cardio", met: 5.0, cardio: true },
  { id: "stair", name: "Stairmaster", muscle: "Cardio", met: 9.0, cardio: true },
  { id: "jumprope", name: "Touwtjespringen", muscle: "Cardio", met: 11.0, cardio: true },
  { id: "hiit", name: "HIIT-training", muscle: "Cardio", met: 10.0, cardio: true },
  { id: "swim", name: "Zwemmen", muscle: "Cardio", met: 7.0, cardio: true },
];

// Voeding per 100 g (kcal, eiwit, koolhydraten, vet)
const FOODS = [
  { name: "Kipfilet (gegrild)", kcal: 165, p: 31, c: 0, f: 3.6 },
  { name: "Kipdijfilet", kcal: 209, p: 26, c: 0, f: 11 },
  { name: "Rundergehakt (mager)", kcal: 214, p: 26, c: 0, f: 12 },
  { name: "Biefstuk", kcal: 175, p: 29, c: 0, f: 6 },
  { name: "Zalm", kcal: 208, p: 20, c: 0, f: 13 },
  { name: "Tonijn (blik, water)", kcal: 116, p: 26, c: 0, f: 1 },
  { name: "Witvis (kabeljauw)", kcal: 82, p: 18, c: 0, f: 0.7 },
  { name: "Garnalen", kcal: 99, p: 24, c: 0.2, f: 0.3 },
  { name: "Ei (heel, ±50g p.st.)", kcal: 155, p: 13, c: 1.1, f: 11 },
  { name: "Eiwit (van ei)", kcal: 52, p: 11, c: 0.7, f: 0.2 },
  { name: "Magere kwark", kcal: 57, p: 10, c: 3.7, f: 0.2 },
  { name: "Griekse yoghurt (0%)", kcal: 59, p: 10, c: 3.6, f: 0.4 },
  { name: "Griekse yoghurt (vol)", kcal: 121, p: 6.4, c: 4, f: 9 },
  { name: "Skyr", kcal: 63, p: 11, c: 4, f: 0.2 },
  { name: "Halfvolle melk", kcal: 46, p: 3.4, c: 4.7, f: 1.5 },
  { name: "Whey proteïne (poeder)", kcal: 380, p: 78, c: 6, f: 5 },
  { name: "Hüttenkäse", kcal: 98, p: 11, c: 3.4, f: 4.3 },
  { name: "Kaas (48+)", kcal: 393, p: 24, c: 0, f: 32 },
  { name: "30+ kaas", kcal: 280, p: 29, c: 0, f: 18 },
  { name: "Tofu", kcal: 76, p: 8, c: 1.9, f: 4.8 },

  { name: "Zilvervliesrijst (gekookt)", kcal: 112, p: 2.6, c: 23, f: 0.9 },
  { name: "Witte rijst (gekookt)", kcal: 130, p: 2.7, c: 28, f: 0.3 },
  { name: "Volkoren pasta (gekookt)", kcal: 124, p: 5, c: 25, f: 1.1 },
  { name: "Pasta (gekookt)", kcal: 158, p: 5.8, c: 31, f: 0.9 },
  { name: "Aardappel (gekookt)", kcal: 87, p: 1.9, c: 20, f: 0.1 },
  { name: "Zoete aardappel", kcal: 86, p: 1.6, c: 20, f: 0.1 },
  { name: "Havermout (droog)", kcal: 379, p: 13, c: 68, f: 6.5 },
  { name: "Volkorenbrood (per snee ±35g)", kcal: 247, p: 10, c: 41, f: 3.5 },
  { name: "Wit brood", kcal: 265, p: 9, c: 49, f: 3.2 },
  { name: "Rijstwafel (±8g p.st.)", kcal: 387, p: 8, c: 81, f: 2.8 },
  { name: "Quinoa (gekookt)", kcal: 120, p: 4.4, c: 21, f: 1.9 },
  { name: "Couscous (gekookt)", kcal: 112, p: 3.8, c: 23, f: 0.2 },
  { name: "Wrap / tortilla", kcal: 310, p: 8, c: 51, f: 8 },

  { name: "Banaan", kcal: 89, p: 1.1, c: 23, f: 0.3 },
  { name: "Appel", kcal: 52, p: 0.3, c: 14, f: 0.2 },
  { name: "Aardbeien", kcal: 32, p: 0.7, c: 7.7, f: 0.3 },
  { name: "Blauwe bessen", kcal: 57, p: 0.7, c: 14, f: 0.3 },
  { name: "Sinaasappel", kcal: 47, p: 0.9, c: 12, f: 0.1 },
  { name: "Druiven", kcal: 69, p: 0.7, c: 18, f: 0.2 },
  { name: "Mango", kcal: 60, p: 0.8, c: 15, f: 0.4 },

  { name: "Broccoli", kcal: 34, p: 2.8, c: 7, f: 0.4 },
  { name: "Spinazie", kcal: 23, p: 2.9, c: 3.6, f: 0.4 },
  { name: "Sperziebonen", kcal: 31, p: 1.8, c: 7, f: 0.2 },
  { name: "Paprika", kcal: 31, p: 1, c: 6, f: 0.3 },
  { name: "Komkommer", kcal: 15, p: 0.7, c: 3.6, f: 0.1 },
  { name: "Tomaat", kcal: 18, p: 0.9, c: 3.9, f: 0.2 },
  { name: "Wortel", kcal: 41, p: 0.9, c: 10, f: 0.2 },
  { name: "Bloemkool", kcal: 25, p: 1.9, c: 5, f: 0.3 },
  { name: "Courgette", kcal: 17, p: 1.2, c: 3.1, f: 0.3 },
  { name: "Avocado", kcal: 160, p: 2, c: 9, f: 15 },

  { name: "Pindakaas", kcal: 588, p: 25, c: 20, f: 50 },
  { name: "Noten (gemengd)", kcal: 607, p: 20, c: 21, f: 54 },
  { name: "Amandelen", kcal: 579, p: 21, c: 22, f: 50 },
  { name: "Olijfolie", kcal: 884, p: 0, c: 0, f: 100 },
  { name: "Boter", kcal: 717, p: 0.9, c: 0.1, f: 81 },
  { name: "Hummus", kcal: 166, p: 8, c: 14, f: 10 },
  { name: "Linzen (gekookt)", kcal: 116, p: 9, c: 20, f: 0.4 },
  { name: "Kikkererwten (gekookt)", kcal: 164, p: 8.9, c: 27, f: 2.6 },
  { name: "Kidneybonen", kcal: 127, p: 8.7, c: 23, f: 0.5 },

  { name: "Chocolade (melk)", kcal: 535, p: 7.7, c: 59, f: 30 },
  { name: "Chocolade (puur)", kcal: 546, p: 4.9, c: 61, f: 31 },
  { name: "Chips", kcal: 536, p: 7, c: 53, f: 34 },
  { name: "Pizza (gemiddeld)", kcal: 266, p: 11, c: 33, f: 10 },
  { name: "Friet", kcal: 312, p: 3.4, c: 41, f: 15 },
  { name: "Hamburger (broodje)", kcal: 254, p: 13, c: 24, f: 12 },
  { name: "Döner / shoarma", kcal: 215, p: 16, c: 13, f: 11 },
  { name: "Proteïnereep", kcal: 380, p: 33, c: 32, f: 12 },
  { name: "Honing", kcal: 304, p: 0.3, c: 82, f: 0 },
  { name: "Jam", kcal: 250, p: 0.3, c: 60, f: 0.1 },
  { name: "Hagelslag", kcal: 440, p: 5, c: 65, f: 17 },
  { name: "Cola", kcal: 42, p: 0, c: 10.6, f: 0 },
  { name: "Cola Zero", kcal: 0.3, p: 0, c: 0, f: 0 },
  { name: "Sinaasappelsap", kcal: 45, p: 0.7, c: 10, f: 0.2 },
  { name: "Bier", kcal: 43, p: 0.5, c: 3.6, f: 0 },
  { name: "Wijn (rood)", kcal: 85, p: 0.1, c: 2.6, f: 0 },
  { name: "Cappuccino (halfvolle melk)", kcal: 37, p: 2, c: 3, f: 1.7 },
];

const MUSCLE_GROUPS = ["Alles", "Borst", "Rug", "Benen", "Schouders", "Biceps", "Triceps", "Core", "Cardio"];
